### PR TITLE
Update I2C core to correct 2 errors & make robust

### PR DESCRIPTION
**Pull request by Tech-TX**
in WAIT_CLOCK_STRETCH(), fix incorrect size of t (unsigned int) comparing to twi_clockStretchLimit (uint32_t)
in Twi::status(), wait for clock stretch to finish before testing SCL and exiting (slave is in unknown state, makes it more robust)
in Twi::status() bus recovery, change final sequence of write_start() to end with write_stop() (this was a mistake, as write_start() leaves SDA low!)
detailed breakdown in the issue,
https://github.com/esp8266/Arduino/issues/6655

### CODE REVIEW

**Comment by TD-er** [comment]
This PR is not to the main repo, but to your own fork.
Maybe you can change the repo where to you want to have this PR set?

**Comment by Tech-TX** [comment]
I thought it was _supposed_ to go in a fork so that I wasn't attempting to modify the real files?
I'm a rank newbie at this, and it seemed like the safest way to do it to allow discussion.  The MERGE options I have are:

merge

and it looks like it should be Squash and merge from those three options.  I'd prefer to not screw it up and cause additional work for someone.

**Comment by TD-er** [comment]
You develop in a fork. But when you're ready for merging it into the original repository, you have to create a pull request to the original repo.

In short the steps (of which some you already did)
- Fork repo
- Create branch at the HEAD of your forked repo
- Start coding
- Commit
- Repeat coding and commit until satisfied
- Create pull request to the main repo
- (optional) get feedback on your PR
- apply feedback into code and commit to the same branch on your repo
- New commits will automatically be added to your PR.

In other words, a pull request is a request to merge a branch into another branch.
The branch you may want to merge into does not have to be the same repository. It can also be the original repo or even a forked one.

A small trick;
If you add a commit to a branch on a forked repo, you may see it also appear as suggestion to create a PR when you visit the original repo page on GitHub: https://github.com/esp8266/Arduino

If this yellow-ish bar does not appear anymore, you can also create a pull request yourself, but it is a bit more work, using this button:
image

**Comment by TD-er** [comment]
Maybe you can still change the "destination" of your pull request here on your own forked page?
Just try to edit this PR.

**Comment by Tech-TX** [comment]
Compile errors, can't currently get the repo to compile.  Gawd, I hate Win10...

**Pull request closed without merging**
